---
- name: Set facts
  set_fact:
    pushgateway_filepath: "{{ prometheus_exporters_common_dist_dir }}/{{ prometheus_pushgateway_release_name }}"
    pushgateway_filename: "{{ prometheus_exporters_common_dist_dir }}/{{ prometheus_pushgateway_release_name }}.tar.gz"

- name: download prometheus pushgateway binary
  get_url:
    url: "https://github.com/prometheus/pushgateway/releases/download/v{{ prometheus_pushgateway_version }}/{{ pushgateway_filename }}"
    dest: "{{ pushgateway_filename }}"

- name: unarchive binary tarball
  unarchive:
    copy: no
    src: "{{ pushgateway_filename }}"
    dest: "{{ prometheus_exporters_common_dist_dir }}"
    creates: "{{ pushgateway_filepath }}/pushgateway"
  register: prometheus_pushgateway_updated
  notify:
    - restart pushgateway

- name: update group and owner for files
  file:
    path: "{{ prometheus_pushgateway_release_name }}"
    state: directory
    recurse: yes
    owner: "{{ prometheus_exporters_common_user }}"
    group: "{{ prometheus_exporters_common_group }}"
  when: prometheus_pushgateway_updated | changed

- name: create symlink to the current release
  file:
    src: "{{ pushgateway_filepath }}"
    path: "{{ prometheus_exporters_common_root_dir }}/pushgateway_current"
    state: link

- name: create systemd service unit
  template:
    src: etc/systemd/system/prometheus-pushgateway.service.j2
    dest: /etc/systemd/system/prometheus-pushgateway.service
    owner: root
    group: root
    mode: 0644
  when: ansible_service_mgr == 'systemd'
  notify:
    - service reenable
    - restart pushgateway

- name: create init service unit
  template:
    src: etc/init/prometheus-pushgateway.conf.j2
    dest: /etc/init/prometheus-pushgateway.conf
    owner: root
    group: root
    mode: 0644
  when: ansible_service_mgr == 'upstart'
  notify:
    - reinit pushgateway
    - restart pushgateway

- meta: flush_handlers

- name: ensure prometheus pushgateway service is enabled and started
  service:
    name: prometheus-pushgateway
    state: started
    enabled: yes
