---

- name: service reenable
  command: systemctl reenable prometheus-pushgateway.service

- name: reinit pushgateway
  command: initctl reload-configuration

- name: restart pushgateway
  service:
    name: prometheus-pushgateway
    state: restarted
